baseURL = "https://example.com/"
title   = "Hugo Rocks!"

# Only home for now, remove what you want.
disableKinds = [
	"taxonomy",
	"term",
	"404",
	"page",
	"robotstxt",
	"rss",
	"section",
	"sitemap",
]
